Fax: true
WindowsBiometricService: true
XblAuthManager: true
XblGameSave: true
MessagingService: true
PrintNotify: true
MapsBroker: true
DiagTrack: true
TabletInputService: true
WIA: true
wisvc: true
SessionEnv: true
CscService: true
WindowsErrorReportingService: true
WaaSMedicSvc: true
PrintSpooler: true
BluetoothSupportService: true
BthServ: true
XboxNetApiSvc: true
XboxGipSvc: true
XboxGameMonitoring: true
RemoteRegistry: true
ConnectedDevicesPlatformService: true
RemoteAccessAutoConnectionManager: true
RemoteAccessConnectionManager: true
RemoteDesktopServices: true
RemoteDesktopServicesUserMode: true
RemoteProcedureCall (RPC) Locator: true
SecondaryLogon: true
WindowsSearch: true
TouchKeyboardAndHandwritingPanelService: true
IPHelper: true
OfflineFiles: true
ParentalControls: true
PeerNetworkingGrouping: true
ProgramCompatibilityAssistantService: true
RetailDemo: true
SensorService: true
SmartCard: true
SmartCardRemovalService: true
WindowsPushNotificationsUserService: true
WMPNetworkSvc: true
