DiagTrack: true
BthServ: true
IPHelper: true
WindowsBiometricService: true
ConnectedDevicesPlatformService: true
WindowsSearch: true
PrintNotify: true
RemoteDesktopServicesUserMode: true
TabletInputService: true
RemoteDesktopServices: true
MessagingService: true
CscService: true
XboxGipSvc: true
WIA: true
WMPNetworkSvc: true
RemoteAccessConnectionManager: true
XblAuthManager: true
PeerNetworkingGrouping: true
SensorService: true
XboxNetApiSvc: true
RemoteAccessAutoConnectionManager: true
XboxGameMonitoring: true
SmartCardRemovalService: true
wisvc: true
MapsBroker: true
WindowsErrorReportingService: true
WaaSMedicSvc: true
RemoteRegistry: true
RemoteProcedureCall (RPC) Locator: true
OfflineFiles: true
PrintSpooler: true
ParentalControls: true
TouchKeyboardAndHandwritingPanelService: true
SessionEnv: true
SmartCard: true
WindowsPushNotificationsUserService: true
Fax: true
SecondaryLogon: true
BluetoothSupportService: true
XblGameSave: true
ProgramCompatibilityAssistantService: true
RetailDemo: true
