CscService: true
XboxGipSvc: true
WindowsBiometricService: true
wisvc: true
BthServ: true
RemoteAccessAutoConnectionManager: true
ConnectedDevicesPlatformService: true
ParentalControls: true
Fax: true
XblGameSave: true
DiagTrack: true
WindowsPushNotificationsUserService: true
PeerNetworkingGrouping: true
XblAuthManager: true
SmartCardRemovalService: true
ProgramCompatibilityAssistantService: true
TouchKeyboardAndHandwritingPanelService: true
WaaSMedicSvc: true
RetailDemo: true
TabletInputService: true
PrintNotify: true
BluetoothSupportService: true
MapsBroker: true
WindowsSearch: true
RemoteAccessConnectionManager: true
SessionEnv: true
XboxGameMonitoring: true
WindowsErrorReportingService: true
SensorService: true
RemoteDesktopServicesUserMode: true
WIA: true
OfflineFiles: true
XboxNetApiSvc: true
PrintSpooler: true
RemoteRegistry: true
IPHelper: true
SmartCard: true
RemoteProcedureCall (RPC) Locator: true
RemoteDesktopServices: true
MessagingService: true
WMPNetworkSvc: true
SecondaryLogon: true
