[package]
name = "w_squid"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
slint = "1.12"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
simplelog = "0.12"
log = "0.4"

[build-dependencies]
slint-build = "1.12"
