[package]
name = "w_squid_frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
chrono = { version = "0.4", features = ["local"] }
